AWSTemplateFormatVersion: '2010-09-09'
Description: Load Balancer Setup

Resources:
  LoadBalancer:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties:
      Name: MyLoadBalancer
      Subnets:
        - !Ref PublicSubnet
      SecurityGroups:
        - !Ref WebServerSG
      Scheme: internet-facing
      Type: application